### ISSUE TITLE
이의제기

### ISSUE THREAD

**Issue by sookyoungwoo** [WaygSite/Wayg_Client#1]
- [ ] #2
- [ ] 여기서 백엔드, 프론트를 구하면 아무도 모르지 않을까요?
- [ ] 디자인도 피그마 링크 공유 부탁합니다.

**Comment by YJH2848** [comment]
아직 피그마 디자인이 끝나지않아 아직 거의 만들지는 않았습니다. 
나중에 어느정도 완성이 되면 vercel로 배포를 할 예정이며 
피그마 링크는 : https://www.figma.com/file/8Az4psq8zR7Ae56HdMonez/%EC%9B%B9%EA%B0%9C%EB%B0%9C-%EC%B7%A8%EC%A4%80%EC%83%9D-2022-2024?node-id=0%3A1&t=2nBrSFWBe2DZiO0C-0 입니다

**Comment by sookyoungwoo** [comment]
감사합니다..*
